"""Fix timestamp timezone

Revision ID: 63f3ac9b81bb
Revises: add_credits_001
Create Date: 2026-01-24 12:55:01.435179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f3ac9b81bb'
down_revision: Union[str, None] = 'add_credits_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('credit_transactions_user_id_fkey', 'credit_transactions', type_='foreignkey')
    op.create_foreign_key('credit_transactions_user_id_fkey', 'credit_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('one_router_payments_user_id_fkey', 'one_router_payments', type_='foreignkey')
    op.create_foreign_key(
        'one_router_payments_user_id_fkey',
        'one_router_payments',
        'users',
        ['user_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_constraint('user_credits_user_id_fkey', 'user_credits', type_='foreignkey')
    op.create_foreign_key('user_credits_user_id_fkey', 'user_credits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_credits_user_id_fkey', 'user_credits', type_='foreignkey')
    op.create_foreign_key('user_credits_user_id_fkey', 'user_credits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('one_router_payments_user_id_fkey', 'one_router_payments', type_='foreignkey')
    op.create_foreign_key('one_router_payments_user_id_fkey', 'one_router_payments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('credit_transactions_user_id_fkey', 'credit_transactions', type_='foreignkey')
    op.create_foreign_key('credit_transactions_user_id_fkey', 'credit_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
