"""add_soft_delete_columns

Revision ID: 9aba0676c496
Revises: 8e7943366bfe
Create Date: 2026-02-02 17:07:13.564248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aba0676c496'
down_revision: Union[str, None] = '8e7943366bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_deleted with server_default for existing rows
    op.add_column('api_keys', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('api_keys', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.create_index('idx_api_keys_not_deleted', 'api_keys', ['user_id', 'is_active'], unique=False, postgresql_where=sa.text('is_deleted = false'))

    op.add_column('provider_credentials', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('provider_credentials', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.create_index('idx_provider_credentials_active', 'provider_credentials', ['user_id', 'provider_name', 'is_active'], unique=False, postgresql_where=sa.text('is_deleted = false'))

    op.add_column('transaction_logs', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('transaction_logs', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.create_index('idx_transaction_logs_active', 'transaction_logs', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('ix_transaction_logs_is_deleted'), 'transaction_logs', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_logs_is_deleted'), table_name='transaction_logs')
    op.drop_index('idx_transaction_logs_active', table_name='transaction_logs', postgresql_where=sa.text('is_deleted = false'))
    op.drop_column('transaction_logs', 'deleted_at')
    op.drop_column('transaction_logs', 'is_deleted')
    op.drop_index('idx_provider_credentials_active', table_name='provider_credentials', postgresql_where=sa.text('is_deleted = false'))
    op.drop_column('provider_credentials', 'deleted_at')
    op.drop_column('provider_credentials', 'is_deleted')
    op.drop_index('idx_api_keys_not_deleted', table_name='api_keys', postgresql_where=sa.text('is_deleted = false'))
    op.drop_column('api_keys', 'deleted_at')
    op.drop_column('api_keys', 'is_deleted')
    # ### end Alembic commands ###
