"""Add environment and features_config columns to provider_credentials

Revision ID: aca6ee819731
Revises: 001_initial
Create Date: 2025-12-16 15:39:08.653681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aca6ee819731'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rate_limit_tracking_api_key_id', table_name='rate_limit_tracking')
    op.drop_index('ix_rate_limit_tracking_api_key_window', table_name='rate_limit_tracking')
    op.drop_table('rate_limit_tracking')
    op.drop_index('idx_service_credentials_user_service_env', table_name='service_credentials')
    op.drop_table('service_credentials')
    op.add_column('api_keys', sa.Column('key_name', sa.String(), nullable=False))
    op.add_column('api_keys', sa.Column('rate_limit_per_min', sa.Integer(), nullable=True))
    op.add_column('api_keys', sa.Column('rate_limit_per_day', sa.Integer(), nullable=True))
    op.add_column('api_keys', sa.Column('expires_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('api_keys', 'environment',
               existing_type=postgresql.ENUM('TEST', 'LIVE', name='environmenttype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_api_keys_user_id', table_name='api_keys')
    op.create_index('idx_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.drop_column('api_keys', 'rate_limit')
    op.drop_column('api_keys', 'updated_at')
    op.drop_column('api_keys', 'ip_whitelist')
    op.drop_column('api_keys', 'name')
    op.add_column('provider_credentials', sa.Column('environment', sa.String(), nullable=False))
    op.add_column('provider_credentials', sa.Column('features_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('provider_credentials', sa.Column('webhook_secret', sa.String(), nullable=True))
    op.add_column('provider_credentials', sa.Column('last_verified_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('provider_credentials', 'encrypted_credential',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('provider_credentials', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_provider_credentials_user_id', table_name='provider_credentials')
    op.drop_index('ix_provider_credentials_user_provider', table_name='provider_credentials')
    op.create_index('idx_provider_credentials_user_provider', 'provider_credentials', ['user_id', 'provider_name'], unique=False)
    op.drop_column('provider_credentials', 'credential_key_id')
    op.add_column('transaction_logs', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('transaction_logs', sa.Column('transaction_id', sa.String(), nullable=False))
    op.add_column('transaction_logs', sa.Column('service_name', sa.String(), nullable=False))
    op.add_column('transaction_logs', sa.Column('provider_txn_id', sa.String(), nullable=True))
    op.add_column('transaction_logs', sa.Column('http_method', sa.String(), nullable=False))
    op.add_column('transaction_logs', sa.Column('response_status', sa.Integer(), nullable=True))
    op.add_column('transaction_logs', sa.Column('response_time_ms', sa.Integer(), nullable=True))
    op.add_column('transaction_logs', sa.Column('status', sa.String(), nullable=False))
    op.add_column('transaction_logs', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('transaction_logs', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('transaction_logs', sa.Column('environment', sa.String(), nullable=False))
    op.alter_column('transaction_logs', 'api_key_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('transaction_logs', 'error_message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_transaction_logs_api_key_created_at', table_name='transaction_logs')
    op.drop_index('ix_transaction_logs_api_key_id', table_name='transaction_logs')
    op.drop_index('ix_transaction_logs_idempotency_key', table_name='transaction_logs')
    op.drop_index('ix_transaction_logs_provider_transaction_id', table_name='transaction_logs')
    op.create_index('idx_transaction_logs_service_name', 'transaction_logs', ['service_name'], unique=False)
    op.create_index('idx_transaction_logs_transaction_id', 'transaction_logs', ['transaction_id'], unique=False)
    op.create_index('idx_transaction_logs_user_created', 'transaction_logs', ['user_id', 'created_at'], unique=False)
    op.create_unique_constraint(None, 'transaction_logs', ['transaction_id'])
    op.create_foreign_key(None, 'transaction_logs', 'users', ['user_id'], ['id'])
    op.drop_column('transaction_logs', 'provider_transaction_id')
    op.drop_column('transaction_logs', 'provider_name')
    op.drop_column('transaction_logs', 'user_ip')
    op.drop_column('transaction_logs', 'idempotency_key')
    op.drop_column('transaction_logs', 'method')
    op.drop_column('transaction_logs', 'status_code')
    op.drop_index('ix_users_clerk_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.create_unique_constraint(None, 'users', ['clerk_user_id'])
    op.add_column('webhook_events', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('webhook_events', sa.Column('service_name', sa.String(), nullable=False))
    op.add_column('webhook_events', sa.Column('event_type', sa.String(), nullable=False))
    op.add_column('webhook_events', sa.Column('signature', sa.String(), nullable=True))
    op.add_column('webhook_events', sa.Column('processed', sa.Boolean(), nullable=True))
    op.add_column('webhook_events', sa.Column('related_txn_id', sa.UUID(), nullable=True))
    op.drop_index('ix_webhook_events_created_at', table_name='webhook_events')
    op.drop_index('ix_webhook_events_provider_processed', table_name='webhook_events')
    op.create_index('idx_webhook_events_user_created', 'webhook_events', ['user_id', 'created_at'], unique=False)
    op.create_foreign_key(None, 'webhook_events', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'webhook_events', 'transaction_logs', ['related_txn_id'], ['id'])
    op.drop_column('webhook_events', 'error')
    op.drop_column('webhook_events', 'is_processed')
    op.drop_column('webhook_events', 'provider_name')
    op.drop_column('webhook_events', 'webhook_signature')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('webhook_signature', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('webhook_events', sa.Column('provider_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('webhook_events', sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('webhook_events', sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'webhook_events', type_='foreignkey')
    op.drop_constraint(None, 'webhook_events', type_='foreignkey')
    op.drop_index('idx_webhook_events_user_created', table_name='webhook_events')
    op.create_index('ix_webhook_events_provider_processed', 'webhook_events', ['provider_name', 'is_processed'], unique=False)
    op.create_index('ix_webhook_events_created_at', 'webhook_events', ['created_at'], unique=False)
    op.drop_column('webhook_events', 'related_txn_id')
    op.drop_column('webhook_events', 'processed')
    op.drop_column('webhook_events', 'signature')
    op.drop_column('webhook_events', 'event_type')
    op.drop_column('webhook_events', 'service_name')
    op.drop_column('webhook_events', 'user_id')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_clerk_id', 'users', ['clerk_user_id'], unique=False)
    op.add_column('transaction_logs', sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transaction_logs', sa.Column('method', postgresql.ENUM('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD', name='httpmethod'), autoincrement=False, nullable=False))
    op.add_column('transaction_logs', sa.Column('idempotency_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transaction_logs', sa.Column('user_ip', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('transaction_logs', sa.Column('provider_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('transaction_logs', sa.Column('provider_transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction_logs', type_='foreignkey')
    op.drop_constraint(None, 'transaction_logs', type_='unique')
    op.drop_index('idx_transaction_logs_user_created', table_name='transaction_logs')
    op.drop_index('idx_transaction_logs_transaction_id', table_name='transaction_logs')
    op.drop_index('idx_transaction_logs_service_name', table_name='transaction_logs')
    op.create_index('ix_transaction_logs_provider_transaction_id', 'transaction_logs', ['provider_transaction_id'], unique=False)
    op.create_index('ix_transaction_logs_idempotency_key', 'transaction_logs', ['idempotency_key'], unique=False)
    op.create_index('ix_transaction_logs_api_key_id', 'transaction_logs', ['api_key_id'], unique=False)
    op.create_index('ix_transaction_logs_api_key_created_at', 'transaction_logs', ['api_key_id', 'created_at'], unique=False)
    op.alter_column('transaction_logs', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('transaction_logs', 'api_key_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('transaction_logs', 'environment')
    op.drop_column('transaction_logs', 'user_agent')
    op.drop_column('transaction_logs', 'ip_address')
    op.drop_column('transaction_logs', 'status')
    op.drop_column('transaction_logs', 'response_time_ms')
    op.drop_column('transaction_logs', 'response_status')
    op.drop_column('transaction_logs', 'http_method')
    op.drop_column('transaction_logs', 'provider_txn_id')
    op.drop_column('transaction_logs', 'service_name')
    op.drop_column('transaction_logs', 'transaction_id')
    op.drop_column('transaction_logs', 'user_id')
    op.add_column('provider_credentials', sa.Column('credential_key_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('idx_provider_credentials_user_provider', table_name='provider_credentials')
    op.create_index('ix_provider_credentials_user_provider', 'provider_credentials', ['user_id', 'provider_name'], unique=False)
    op.create_index('ix_provider_credentials_user_id', 'provider_credentials', ['user_id'], unique=False)
    op.alter_column('provider_credentials', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('provider_credentials', 'encrypted_credential',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    op.drop_column('provider_credentials', 'last_verified_at')
    op.drop_column('provider_credentials', 'webhook_secret')
    op.drop_column('provider_credentials', 'features_config')
    op.drop_column('provider_credentials', 'environment')
    op.add_column('api_keys', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('api_keys', sa.Column('ip_whitelist', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('api_keys', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('api_keys', sa.Column('rate_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('idx_api_keys_user_id', table_name='api_keys')
    op.drop_index('idx_api_keys_key_hash', table_name='api_keys')
    op.create_index('ix_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('api_keys', 'environment',
               existing_type=sa.String(),
               type_=postgresql.ENUM('TEST', 'LIVE', name='environmenttype'),
               existing_nullable=False)
    op.drop_column('api_keys', 'expires_at')
    op.drop_column('api_keys', 'rate_limit_per_day')
    op.drop_column('api_keys', 'rate_limit_per_min')
    op.drop_column('api_keys', 'key_name')
    op.create_table('service_credentials',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('environment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('credentials_encrypted', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('features_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('webhook_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='service_credentials_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_credentials_pkey')
    )
    op.create_index('idx_service_credentials_user_service_env', 'service_credentials', ['user_id', 'service_name', 'environment'], unique=False)
    op.create_table('rate_limit_tracking',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('api_key_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('request_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name='rate_limit_tracking_api_key_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rate_limit_tracking_pkey')
    )
    op.create_index('ix_rate_limit_tracking_api_key_window', 'rate_limit_tracking', ['api_key_id', 'window_start'], unique=False)
    op.create_index('ix_rate_limit_tracking_api_key_id', 'rate_limit_tracking', ['api_key_id'], unique=False)
    # ### end Alembic commands ###
