"""add_idempotency_keys_table

Revision ID: e7d4f554727d
Revises: 1a033a429620
Create Date: 2025-12-26 14:09:14.796425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e7d4f554727d'
down_revision: Union[str, None] = '1a033a429620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('api_key_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('idempotency_key', sa.String(), nullable=False),
        sa.Column('endpoint', sa.String(), nullable=False),
        sa.Column('request_hash', sa.String(), nullable=False),
        sa.Column('response_body', sa.Text(), nullable=True),
        sa.Column('response_status_code', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create index on (api_key_id, idempotency_key) for efficient lookups
    op.create_index('idx_idempotency_keys_api_key_idempotency', 'idempotency_keys', ['api_key_id', 'idempotency_key'], unique=False)

    # Create index on expires_at for cleanup queries
    op.create_index('idx_idempotency_keys_expires_at', 'idempotency_keys', ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_idempotency_keys_expires_at', table_name='idempotency_keys')
    op.drop_index('idx_idempotency_keys_api_key_idempotency', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
